### PR TITLE
CBS-566 Products using identity v1.1 API need to migrate to v2.0 

### PR DESCRIPTION
**Pull request by saumyaSgupta**
JIRA url: https://jira.rax.io/browse/CBS-566
changes done were removing dependency on Identityv1.1 , adding default auth_url for swift

### CODE REVIEW

**Comment by cbs-cicd** [comment]
Added link-backs to the following issues:

* jira
  * https://jira.rax.io/browse/CBS-566

**Comment by cbs-cicd** [comment]
Triggering unit tests...

{{{test:queued:931}}}

**Comment by cbs-cicd** [comment]
Running tests with './.unittests'...

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunr-change/24/consoleFull

{{{test:started:24}}}

**Comment by cbs-cicd** [comment]
Test suite passed!

For more details, see: http://jarvis.cbs.racklabs.com:8080/job/test-lunr-change/24/consoleFull

{{{test:complete}}}

**Comment by SaumyaRackspace** [comment]
Closing this PR , as it has been raised with wrong user

**Pull request closed without merging**
